#!/usr/bin/env zsh

# if there isn't an argument, print usage and exit
if [[ $# -ne 1 ]]; then 
    echo "usage: fizzbuzz <number>"
    exit 1
fi

# get numebr to print up to from the first argument (interpret as a number)
((NUM=$1))

# helper function to process fizzbuzz logic for a single number
fb() {
    if [[ $(( $1 % 15 )) -eq 0 ]]; then
        echo "Fizzbuzz"
    elif [[ $(( $1 % 3 )) -eq 0 ]]; then
        echo "Fizz"
    elif [[ $(( $1 % 5 )) -eq 0 ]]; then
        echo "Buzz"
    else
        echo "$1"
    fi
}

# while loop approach to count up to NUM from 1
N=1
while [[ $N -le $NUM ]]; do
    fb $N
    ((N = $N + 1))
done

# # ranged for approach to count up to NUM from 1
# for N in {1..$NUM}; do
#     fb $N
# done
